stages:
  - build

default:
  tags:
    - ci

build:
  stage: build
  image: node:14.16.0-buster
  before_script:
    - curl -f https://get.pnpm.io/v6.16.js | node - add --global pnpm@7
    - pnpm config set store-dir .pnpm-store
  script:
    - pnpm install # install dependencies
    - pnpm start:dev
  cache:
    key:
      files:
        - pnpm-lock.yaml
    paths:
      - .pnpm-store